version: '3.9'
services:
  solana-rpc-proxy:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    environment:
      - 'PORT=8080'
      - 'SOLANA_RPC_URL=http://api.devnet.solana.com/'
    networks:
      - 'solana-rpc'
networks:
  solana-rpc:
